version: '3.4'

services:
  database:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=users_microservice
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - '/var/lib/postgresql/data'

  usersservice:
    image: emilyhosoya/usersservice
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - 'database'
    environment:
      NODE_ENV: production
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8080:8080'
      
volumes:
  db_data: {}